[font]
normal = { family = "FantasqueSansM Nerd Font Mono", style = "Regular" }
size = 16
# Penguin "ðŸ§", iIlL => 0Oo

[terminal]
shell = "tmux"

[window]
dynamic_padding = true

[cursor]
style = {shape = "Beam", blinking = "Off"}
vi_mode_style = {shape = "Block", blinking = "Off"}
unfocused_hollow = false

[keyboard]
bindings = [
    { key = "Back", mods = "Control", chars = "\u0017" },
    { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
    { key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~" },
    { key = "Enter", mods = "Control", chars = "\u001b[20;5~" },
    { key = "Enter", mods = "Shift", chars = "\u001b[20;2~" },
]

# Everforest Dark
[colors]
cursor = {cursor = "#d3c6aa"}
[colors.primary]
background = '#2d353b'
foreground = '#d3c6aa'
dim_foreground = "#7a8478"
[colors.normal]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'
[colors.bright]
black   = '#4f585e'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

# Light theme
# [colors.primary]
# background = '#F7F7F7'
# foreground = '#434343'
#
# [colors.cursor]
# text = '#F7F7F7'
# cursor = '#434343'
#
# [colors.normal]
# black = '#000000'
# red = '#AA3731'
# green = '#448C27'
# yellow = '#CB9000'
# blue = '#325CC0'
# magenta = '#7A3E9D'
# cyan = '#0083B2'
# white = '#BBBBBB'
#
# [colors.bright]
# black = '#777777'
# red = '#F05050'
# green = '#60CB00'
# yellow = '#FFBC5D'
# blue = '#007ACC'
# magenta = '#E64CE6'
# cyan = '#00AACB'
# white = '#FFFFFF'

[env]
TERM = "xterm-256color"
